apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk1
  labels:
    app: zk1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk1
  template:
    metadata:
      labels:
        app: zk1
    spec:
      containers:
      - name: kafka
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
          name: first
        - containerPort: 2888
          name: second
        - containerPort: 3888
          name: third
        env:
          - name: ZOO_SERVER_ID
            value: "1"
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
          - name: ZOO_SERVERS
            value: "0.0.0.0:2888:3888,zk2-service:2888:3888,zk3-service:2888:3888"
---
apiVersion: v1
kind: Service
metadata:
  name: zk1-service
spec:
  selector:
    app: zk1
  ports:
    - protocol: TCP
      name: first
      port: 2181
      targetPort: 2181
    - protocol: TCP
      name: second
      port: 2888
      targetPort: 2888
    - protocol: TCP
      name: third
      port: 3888
      targetPort: 3888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk2
  labels:
    app: zk2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk2
  template:
    metadata:
      labels:
        app: zk2
    spec:
      containers:
      - name: kafka
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
          name: first
        - containerPort: 2888
          name: second
        - containerPort: 3888
          name: third
        env:
          - name: ZOO_SERVER_ID
            value: "2"
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
          - name: ZOO_SERVERS
            value: "zk1-service:2888:3888,0.0.0.0:2888:3888,zk3-service:2888:3888"
---
apiVersion: v1
kind: Service
metadata:
  name: zk2-service
spec:
  selector:
    app: zk2
  ports:
    - protocol: TCP
      name: first
      port: 2181
      targetPort: 2181
    - protocol: TCP
      name: second
      port: 2888
      targetPort: 2888
    - protocol: TCP
      name: third
      port: 3888
      targetPort: 3888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk3
  labels:
    app: zk3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk3
  template:
    metadata:
      labels:
        app: zk3
    spec:
      containers:
      - name: kafka
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
          name: first
        - containerPort: 2888
          name: second
        - containerPort: 3888
          name: third
        env:
          - name: ZOO_SERVER_ID
            value: "3"
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
          - name: ZOO_SERVERS
            value: "zk1-service:2888:3888,zk2-service:2888:3888,0.0.0.0:2888:3888"
---
apiVersion: v1
kind: Service
metadata:
  name: zk3-service
spec:
  selector:
    app: zk3
  ports:
    - protocol: TCP
      name: first
      port: 2181
      targetPort: 2181
    - protocol: TCP
      name: second
      port: 2888
      targetPort: 2888
    - protocol: TCP
      name: third
      port: 3888
      targetPort: 3888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc1
  labels:
    app: kfc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfc1
  template:
    metadata:
      labels:
        app: kfc1
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        ports:
        - containerPort: 80
        env:
          - name: KAFKA_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "zk1-service:2181"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9093"
          - name: KAFKA_CFG_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9093"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "CLIENT"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc2
  labels:
    app: kfc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfc2
  template:
    metadata:
      labels:
        app: kfc2
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        ports:
        - containerPort: 80
        env:
          - name: KAFKA_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "zk2-service:2181"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9094"
          - name: KAFKA_CFG_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9094"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "2"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "CLIENT"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc3
  labels:
    app: kfc3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfc3
  template:
    metadata:
      labels:
        app: kfc3
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        ports:
        - containerPort: 80
        env:
          - name: KAFKA_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "zk3-service:2181"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9095"
          - name: KAFKA_CFG_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9095"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "3"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "CLIENT"
      restartPolicy: Always
