apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk1
  labels:
    app: zk1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk1
  template:
    metadata:
      labels:
        app: zk1
    spec:
      containers:
      - name: kafka
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
          name: first
        - containerPort: 2888
          name: second
        - containerPort: 3888
          name: third
        env:
          - name: ZOO_SERVER_ID
            value: "1"
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zk1-service
spec:
  selector:
    app: zk1
  ports:
    - protocol: TCP
      name: first
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc1-zk1
  labels:
    app: kfc1-zk1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfc1-zk1
  template:
    metadata:
      labels:
        app: kfc1-zk1
    spec:
      containers:
      - name: redir4
        image: library/redir4:latest
        ports:
        - containerPort: 2181
        imagePullPolicy: Never
        env:
          - name: REDIR_PORT
            value: "2181"
          - name: REDIR_DEST
            value: "zk1-service:2181"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kfc1-zk1-service
spec:
  selector:
    app: kfc1-zk1
  ports:
    - protocol: TCP
      name: first
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfc1
  labels:
    app: kfc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfc1
  template:
    metadata:
      labels:
        app: kfc1
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka
        ports:
        - containerPort: 80
        env:
          - name: KAFKA_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "kfc1-zk1-service:2181"
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9093"
          - name: KAFKA_CFG_LISTENERS
            value: "CLIENT://$(KAFKA_POD_IP):9090,EXTERNAL://localhost:9093"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "CLIENT"
      restartPolicy: Always